# Generated by Django 5.0.3 on 2024-04-11 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0006_comment_remove_food_comment_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programming_cocoment",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cocoments",
                to="blogapp.programming_comment",
            ),
            preserve_default=False,
        ),
    ]
