# Generated by Django 5.0.3 on 2024-04-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0007_programming_cocoment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programming_comment",
            old_name="food",
            new_name="programming",
        ),
    ]
