# Generated by Django 5.0.3 on 2024-04-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0008_rename_food_programming_comment_programming"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hobby_cocoment",
            name="comment_ptr",
        ),
        migrations.RemoveField(
            model_name="hobby_cocoment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="programming_cocoment",
            name="comment_ptr",
        ),
        migrations.RemoveField(
            model_name="programming_cocoment",
            name="parent",
        ),
        migrations.DeleteModel(
            name="Food_Cocoment",
        ),
        migrations.DeleteModel(
            name="Hobby_Cocoment",
        ),
        migrations.DeleteModel(
            name="Programming_Cocoment",
        ),
    ]
