# Generated by Django 5.0.3 on 2024-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0009_remove_hobby_cocoment_comment_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hobby_comment",
            name="comment_ptr",
        ),
        migrations.RemoveField(
            model_name="programming_comment",
            name="comment_ptr",
        ),
        migrations.RemoveField(
            model_name="food_comment",
            name="comment_ptr",
        ),
        migrations.RenameField(
            model_name="programming_comment",
            old_name="programming",
            new_name="Programming",
        ),
        migrations.AddField(
            model_name="food_comment",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="food_comment",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="food_comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="food_comment",
            name="writer",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hobby_comment",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hobby_comment",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hobby_comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hobby_comment",
            name="writer",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programming_comment",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programming_comment",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="programming_comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programming_comment",
            name="writer",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
