# Generated by Django 5.0.4 on 2024-04-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hwApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="detail",
            new_name="content",
        ),
    ]
