# Generated by Django 5.0.4 on 2024-04-07 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hwApp", "0002_rename_detail_todo_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
