# Generated by Django 5.0.3 on 2024-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_food_hobby_programming_delete_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="hobby",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="programming",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
