# Generated by Django 5.0.3 on 2024-04-03 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_food_time_hobby_time_programming_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="hobby",
            old_name="time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="programming",
            old_name="time",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="food",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hobby",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="programming",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
